import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/otra1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Gonzalo Volonterio | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TransitionEffect />
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light '>
        <Layout className='pt-0 md:p-16 sm:p-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-[85%] image-overlay inset-0 pointer-events-none'>
              <Image
                src={profilePic}
                alt='GonzaloVolonterio-dev'
                className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes='(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw'
              />
            </div>
            <div className='w-1/2 space-x-2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text='Turning dreams into reality through programming.'
                delay={800}
                className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              '
              />
              <p className='my-4 text-base space-x-2 font-medium md:text-sm sm:text-xs text-justify  whitespace-normal'>
                Welcome to my portfolio! I am a passionate Full Stack Developer
                with a background in UX/UI design, dedicated to creating
                engaging and user centered digital experiences. With a solid
                foundation in Front End and Back End development, I blend my
                technical expertise with a fresh perspective on UX/UI design to
                deliver intuitive and visually appealing interfaces. Explore my
                more recent projects, showing my experience in web and mobile
                development.
              </p>
              <div className='flex items-center space-x-4 self-start mt-2 lg:self-center'>
                <Link
                  href='/CV.Volonterio.Gonzalo.pdf'
                  target={'_blank'}
                  aria-label='My Cv'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                '
                  download={true}
                >
                  Summary <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link
                  href='mailto:volonteriogonzalo.dev@gmail.com'
                  target={'_blank'}
                  aria-label='To talk to me'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                '
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  );
}
