import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/pp.jpg';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sintayehu Fantaye | Portfolio</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TransitionEffect />
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light '>
        <Layout className='pt-0 md:p-16 sm:p-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
          <div
              className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark
            bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8
            '
            >
              <div className='absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-black dark:bg-light' />
              <Image
                src={profilePic}
                alt='gonzalovolonterio-dev'
                className='w-full h-auto rounded-2xl'
                priority
                sizes='(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw'
              />
            </div>
           
            <div className='w-1/2 space-x-2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text='Forging the Future: Where Data Meets Intelligence.'
                delay={800}
                className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              '
              />
              <p className='my-4 text-base space-x-2 font-medium md:text-sm sm:text-xs text-justify  whitespace-normal'>
                Welcome to my portfolio! As a seasoned backend developer, I form the bedrock
                 of technological innovation, driving the engines that power the digital age. 
                 In the grand orchestra of data, I play the conductor, orchestrating the harmonious 
                 blend of backend wizardry, data science finesse, and ML prowess.

                  My canvas is the intricate labyrinth of code, where I meticulously craft and 
                    optimize systems to perfection. Each project becomes an opportunity to infuse 
               data science and ML intelligence into the heart of the backend,
                   reshaping the way we interact with technology
              </p>
              <div className='flex items-center space-x-4 self-start mt-2 lg:self-center'>
                <Link
                  href='/CV.Volonterio.Gonzalo.pdf'
                  target={'_blank'}
                  aria-label='My Cv'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                '
                  download={true}
                >
                  Resume <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link
                  href='mailto:volonteriogonzalo.dev@gmail.com'
                  target={'_blank'}
                  aria-label='To talk to me'
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base
                '
                >
                  Contact
                </Link>
              </div>
            </div>
            
          </div>
          
        </Layout>

        <HireMe />
      </main>
    </>
  );
}
